# Usamos un servidor web ligero
FROM nginx:alpine

# Copiamos el archivo HTML a la carpeta pública del servidor web
COPY index.html /usr/share/nginx/html/

# Exponemos el puerto estándar de internet (80)
EXPOSE 80