version: '3.8'

services:
  # 1. El Backend (API RESTful)
  mi-servidor-ubb:
    build: ./backend
    container_name: servidor-api-ubb
    ports:
      - "8000:8000"
    networks:
      - red-campus

  # 2. El Simulador de la Cámara (Edge Node)
  nodo-simulador:
    build: ./simulador
    container_name: camara-simulada
    depends_on:
      - mi-servidor-ubb
    networks:
      - red-campus

  # 3. ¡NUEVO! La Plataforma Web (Frontend)
  plataforma-web:
    build: ./frontend
    container_name: frontend-ubb
    ports:
      - "8080:80"  # Lo abrimos en el puerto 8080 de tu PC, apuntando al 80 de Nginx
    depends_on:
      - mi-servidor-ubb
    networks:
      - red-campus

networks:
  red-campus:
    driver: bridge